---
- name: Update cosmosgov_web page
  hosts: cosmosgov_web
  become: true
  gather_facts: false
  pre_tasks:
    - name: update and upgrade
      apt:
        upgrade: dist
        update_cache: true
  roles:
    - update


